version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sql:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Qwer?1234
      hostname: sql

  shopsrusdiscounts.api:
    image: ${DOCKER_REGISTRY-}shopsrusdiscounts
    build:
      context: .
      dockerfile: src/ShopsRUsDiscounts.Api/Dockerfile
    depends_on:  
      - "sql"
      - "rabbitmq"
