version: '3.4'

services:
  shopsrusdiscounts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5001:80"
      - "5002:443"
